amazon_project/activite4.3/src/Entity/Product.php
<?php
namespace App\Entity;
use App\Repository\ProductRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProductRepository::class)
 */
class Product
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Label;

    /**
     * @ORM\Column(type="integer")
     */
    private $Price;

    /**
     * @ORM\Column(type="integer")
     */
    private $Quantity;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="products")
     * @ORM\JoinColumn(nullable=false)
     */
    private $category;



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLabel(): ?string
    {
        return $this->Label;
    }

    public function setLabel(string $Label): self
    {
        $this->Label = $Label;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->Price;
    }

    public function setPrice(int $Price): self
    {
        $this->Price = $Price;

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->Quantity;
    }

    public function setQuantity(int $Quantity): self
    {
        $this->Quantity = $Quantity;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    
}

amazon_project/activite4.3/src/Controller/ProductController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\Persistence\ManagerRegistry;
use App\Entity\Product;
use App\Entity\Category;
use  App\Repository\CategoryRepository;
use  App\Repository\ProductRepository;

class ProductController extends AbstractController
{
    /**
     * @Route("/product", name="app_product")
     */
    public function index(): Response
    {
        return $this->render('product/index.html.twig', [
            'controller_name' => 'ProductController',
        ]);
    }

     /**
     * @Route("/createproduct", name="product")
     */
    public function create(ManagerRegistry $doctrine, CategoryRepository $categoryRepository): Response
    {
    
        $category=$categoryRepository->findCategoryById(1);
        $product = new Product();
        $product->setLabel('robe');
        $product->setPrice(200);
        $product->setQuantity(5);
        // relates this product to the category
        $product->setCategory($category);
        $entityManager = $doctrine->getManager();
        $entityManager->persist($category);
        $entityManager->persist($product);
        $entityManager->flush();

        return new Response(
            'Saved new product with id: '.$product->getId()
            .' and new category with id: '.$category->getId()
        );
    }
/**
     * @Route("/get-all-products", name="get-all-products")
     */
    public function getproduct(): Response
    {
        $repo=$this->getDoctrine()->getRepository(Product::class);
        $products=$repo->findAll();
        return $this->render('product/index.html.twig', [
            'controller_name' => 'productController',
            'products' =>$products
        ]);
      
    }
/**
     * @Route("/productsbycategory/{category_id}", name="get-category-products")
     */
    public function showProducts(ManagerRegistry $doctrine, ProductRepository $produitRepository, int $category_id): Response
    {
        $produits = $produitRepository->findBy(['category' => $category_id]);
        return $this->render('product/index.html.twig', [
            'controller_name' => 'productController',
            'products' =>$produits
        ]);
       
    }

}

amazon_project/activite4.3/templates/product/detail.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ product.label }}{% endblock %}
{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">

    <div class="container">
        <div class="row mt-3 mb-4">
            <div class="col-md-4">
                <img src="" alt="{{ product.Label}}" class="img-fluid">
            </div>
            <div class="col-md-8">
                <h1 class="mt-4 mt-md-0">{{ product.Label}}</h1>
                <h2>{{ product.price }} DT</h2>
                <hr>
                <b>quantity: </b>{{ product.Quantity}}
                <form class="mt-4 p-4 bg-light" method="post">
                    <div class="form-group">
                        <label for="quantity">Quantity</label>
                        <input type="number" class="form-control" id="quantity">
                    </div>
                    <button class="btn btn-warning">Add to Cart</button>
                </form>
            </div>
        </div>
    </div>
{# {% endblock %} #}

<div class="example-wrapper">

{% for key, product in products %}
   {% if key < 5 %}
   <div class="card border-info mb-3" style="max-width: 20rem;">
        <h5 class="card-header">product:</h5>
        <div class="card-body">
          <h3 class="card-title">{{ product.Label}}</h3>
        {# <h5 class="card-title"> Category {{ product.category}}</h5> #}
 </div>
    <div class="card-body">
    <p class="card-text">Price: {{ product.Price}}  dt</p>
  </div>
    <ul class="list-group list-group-flush">
    <li class="list-group-item">quantity : {{ product.Quantity}}</li>
  </ul>
    <div class="card-footer text-muted">

    </div>
</div>
{% endif %}
{% endfor %}

</div>
{% endblock %}

amazon_project/activite4.3/templates/product/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ProductController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif;   }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">

{% for product in products %}
   
   <div class="card border-info mb-3" style="max-width: 20rem;">
        <h5 class="card-header">product:</h5>
        <div class="card-body">
          <h3 class="card-title">{{ product.Label}}</h3>
        {# <h5 class="card-title"> Category {{ product.category}}</h5> #}
 </div>
    <div class="card-body">
    <p class="card-text">Price: {{ product.Price}}  dt</p>
  </div>
    <ul class="list-group list-group-flush">
    <li class="list-group-item">quantity : {{ product.Quantity}}</li>
  </ul>
    <div class="card-footer text-muted">

    </div>
</div>
{% endfor %}

</div>
{% endblock %}